### ISSUE TITLE
https://cgit.freedesktop.org is down

### ISSUE THREAD

**Issue by rakuri255** [dr-leo/PyHyphen#21]
The server https://cgit.freedesktop.org is down

**Comment by simonseyock** [comment]
This makes the library for other languages than english almost unusable at the moment. Do any mirrors of this server exist?

**Comment by dr-leo** [comment]
Fixed in PR22. I am about to do a buck fix release today.Am 30.07.2024 um 10:31 schrieb Simon Seyock ***@***.***>:﻿
This makes the library almost unusable at the moment. Do any mirrors of this server exist?

**Comment by rakuri255** [comment]
Its already fixed with https://github.com/dr-leo/PyHyphen/pull/22

**Comment by simonseyock** [comment]
Ah that's nice! Thanks a lot

**Comment by dr-leo** [comment]
The releases out. Please let me know if any issues remain.Am 30.07.2024 um 10:31 schrieb Simon Seyock ***@***.***>:﻿
This makes the library almost unusable at the moment. Do any mirrors of this server exist?

**Comment by simonseyock** [comment]
Everything works again, thanks.
